# Generated by Django 4.1.7 on 2023-02-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentRaiting',
            new_name='ContentRating',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='contentRaiting',
            new_name='contentRating',
        ),
    ]
